### ISSUE TITLE
Decombinator compatibility with Biopython

### ISSUE THREAD

**Issue by TahelRonel** [innate2adaptive/decombinator#28]
A change made in Biopython 1.78 (released Sept 2020) means this version of the package is not compatible with previous versions of Decombinator (up to and including V4.0.2). 
Decombinator V4.0.3 has been updated to work with this latest Biopython release.
We aim to keep Decombinator up-to-date with the latest versions of all packages. We have included in the README the most recently tested version numbers of the non-standard packages required for Decombinator.

**Comment by mvcowley** [comment]
Issue seems successfully resolved.
