### ISSUE TITLE
Downstream analysis

### ISSUE THREAD

**Issue by benjytan88** [innate2adaptive/decombinator#30]
Hi, 
I recently got a dataset from our collaborator who processed bulk TCR-Seq using Decombinator. I read in your publication that the data is AIRR-compatible but when I tried loading it in R using `immunarch`, I couldn't do so as some columns are missing. Can you recommend any packages / programs to perform downstream analysis for your data (i.e. calculating clonality, diversity, repertoire similarities, etc...)?

**Comment by JamieHeather** [comment]
I don't use any third party tools downstream so I can't recommend any - perhaps the other authors can. 

However I just checked the current AIRR-C schema and all the required fields are present in Decombinator output, assuming your collaborator used an up-to-date version. I can't get `immunarch` installed on the current version of R, so I can't test this myself: what fields does it say are missing? Have you tried adding those columns yourself?

**Comment by benjytan88** [comment]
Hi @JamieHeather ,
Thanks for your quick reply! I never thought of adding the columns myself as I have the assumption that empty columns won't work. But, I tried it as per your suggestion and apparently it works! FYI, the missing columns are `cdr1, cdr2, fwr1, fwr2, fwr3, fwr4, fwr1_aa, fwr2_aa, fwr3_aa `and `fwr4_aa`. 
I'm going to close this now. Thanks again!

**Comment by JamieHeather** [comment]
Happy to help, and thanks for letting us know!

In case it's helpful in future, it's worth knowing that the [AIRR-C schema](https://docs.airr-community.org/en/stable/datarep/rearrangements.html) often basically forces a bunch of empty columns, as a lot of the 'required' columns (which are supposed to always be present) aren't relevant to all analyses. There's also a bunch of additional 'optional' columns (which includes all of those you list) which don't need to be present - so this is maybe just a case of `immunarch` being a little over-zealous in its expectations.
